### ISSUE TITLE
Is there any api to write the task's trace to trace visualization server ? Not every time copy the JSON trace into the "Insert JSON trace here" box.

### ISSUE THREAD

**Issue by notatent** [linkedin/parseq#114]
HI,   Is there any api to write the task's trace to trace visualization server ? Not every time copy the JSON trace into the "Insert JSON trace here" box  by hand.

**Comment by notatent** [comment]
or, Is there any monitor server just like parseq-tracevis-server? but monitor all the task's trace info.

**Comment by jodzga** [comment]
Hi, could you please explain in more details what API are you looking for and how would you use it? I don't quite understand your use case.

**Comment by notatent** [comment]
Thanks for you answer my question!  I'm mean when I using the ParSeq in my application, is there any tools to collect all the tasks trace info, and show them in the web page, just like contrib/parseq-tracevis-server. But show it by user's application calling ParSeq's API, not copy the generated JSON trace into the "Insert JSON trace here" box by hand. Thanks again.

**Comment by jodzga** [comment]
We have a support for a part of what you need. EngineBuilder has a method `setPlanCompletionListener()`. Once set, `PlanCompletionListener` will be called after the Task passed to the Engine for execution is completed. This is a good place to obtain a Trace and write it somewhere. We don't have however any support for storing and handling a collection of traces in our visualization tools.
