### ISSUE TITLE
Add Task.sideEffect()

### ISSUE THREAD

**Issue by jodzga** [linkedin/parseq#132]
Existing API to create a side effect is Task.withSideEffect(). It requires an existing Task instance to begin with what leads to unnatural constructs such as: Task.value(null).withSideEffect().
ParSeq should provide an API for creating side effect in situations where there is no existing Task instance.

**Comment by saponniah** [comment]
Can the usecase for using `Task.value(null).withSideEffect()` be achieved by `Task.action()`? How will the new `Task.sideEffect()` be different? The only difference I see is that the `Task<Void>` returned from `action()` will be marked as failed during a failure when the current side effect task's completion status is never exposed.

**Comment by jodzga** [comment]
The Task.withSideEffect() have behavior that is very different than "non side effect" task: http://linkedin.github.io/parseq/javadoc/latest/com/linkedin/parseq/Task.html#withSideEffect-java.lang.String-com.linkedin.parseq.function.Function1-

**Comment by junchuanwang** [comment]
Close this as already implemented in #204
