### ISSUE TITLE
Split existing batches according to maxBatchSize configuration in ParSeqRestClient

### ISSUE THREAD

**Issue by jodzga** [linkedin/parseq#142]
Currently maxBatchSize does not affect existing batch GET requests. It is only used to limit size of batch requests created as a result of aggregation, see:
https://github.com/linkedin/parseq/blob/1608fb0ab70b8d68aa061bd9ac71defce027dc0f/contrib/parseq-batching/src/main/java/com/linkedin/parseq/batching/BatchImpl.java#L188

This change is to make sure that all outgoing batch GET requests have size below maxBatchSize even if original batch GET request had a larger size.

**Comment by mchen07** [comment]
We have decided to document this in parseq-restli-client README.md for this behavior, this has been committed in master.
