### ISSUE TITLE
broken link in user guide doc

### ISSUE THREAD

**Issue by naama11** [linkedin/parseq#157]
Hi guys
the following link in the user guide is broken:
WrappedRequestBuilder.
Looking for async task execution with callback example.
Thanks

**Comment by jodzga** [comment]
Thanks for pointing this out.
The working link is:
https://github.com/linkedin/parseq/blob/master/contrib/parseq-http-client/src/main/java/com/linkedin/parseq/httpclient/WrappedRequestBuilder.java

I'll fix the wiki ASAP.

**Comment by jodzga** [comment]
Wiki is fixed now. Thanks again for reporting this.
