### ISSUE TITLE
Names in tracevis' waterfall view are truncated

### ISSUE THREAD

**Issue by jodzga** [linkedin/parseq#162]
We have some fairly large parseq traces coming from ReMix workflows that also have descriptive task names, but tracevis currently truncates the visualization past a certain width:

![screenshot-70](https://user-images.githubusercontent.com/2935153/36918950-6d177bd8-1e10-11e8-9da0-59fd9feb0f86.png)

**Comment by mchen07** [comment]
This has been fixed.
