### ISSUE TITLE
Add javadoc to ParSeqRestClient and ParSeqRestliClient that explain error handling

### ISSUE THREAD

**Issue by jodzga** [linkedin/parseq#163]
It is not obvious what conditions may trigger what kind of exceptions.

**Comment by jodzga** [comment]
ParSeqRestClient delegates to Rest.li Client sendRequest method that takes callback. It has the following documentation:

In the event of an error, the callback will receive a com.linkedin.r2.RemoteInvocationException. If a valid error response was received from the remote server, the callback will receive a RestLiResponseException containing the error details.

My understanding is that if server throws RestliServiceException with status code 4xx or 5xx then this will result in client callback's onError(RestLiResponseException) invokaction (that means task will fail). It is not clear what happens when server throws RestliServiceException with status code different than 4xx and 5xx or even if it is possible.

Aside from RestLiResponseException a ParSeqRestClient  may fail with other kinds of exceptions:
-	TimeoutException - when request times out
-	RestLiResponseException - when server throws RestliServiceException 
-	ServiceUnavailableException - when client can't find available server instance that could serve the request
-	RemoteInvocationException - when call failed for other reasons

**Comment by hiteshsharma** [comment]
Also what happens if a 4xx or 5xx is thrown by server without a
RestliServiceException? Is a RestliServiceException required for the
ParSeqRestClient to fail?

**Comment by mchen07** [comment]
IN this case, client will still get RestLiResponseException as well from HttpBridge status check, and thus it will still fail.

**Comment by mchen07** [comment]
I have added javadoc in ParSeqRestClient: https://github.com/linkedin/parseq/blob/master/contrib/parseq-restli-client/src/main/java/com/linkedin/restli/client/ParSeqRestClient.java#L46, thus closing this issue.
