### ISSUE TITLE
Convert contrib maven project to gradle

### ISSUE THREAD

**Issue by bolobobo** [linkedin/parseq#180]
All the contrib projects are built by maven now.  Since they have almost the same structure, once we finish one project, it maybe easy to do others.

- [ ] parseq-batching
- [ ] parseq-benchmark
- [ ] parseq-examples  (needn't publish to maven central)
- [ ] parseq-exec
- [ ] parseq-http-client
- [ ] parseq-lambda-names
- [ ] parseq-legacy-examples (needn't publish to maven central)
- [ ] parseq-restli-client
- [ ] parseq-tracevis-server (have to pay attention to the building of jar-with-dependecies jar files)
- [ ] parseq-zk-client

**Comment by hiteshsharma** [comment]
Is this still open? I can take a few of these tasks as an initial task to start contributing to parseq. Assign as you may see fit

**Comment by mchen07** [comment]
@hiteshsharma This task is already done. Latest parseq code has been migrated to use gradle to build.
