### ISSUE TITLE
Provide an API withDelay to delay running a task after given time period

### ISSUE THREAD

**Issue by mchen07** [linkedin/parseq#210]
`Context.createTimer` function provides a way for parseq users to delay running a task by certain amount of time. But this API is not obvious to user. It would be good if we can provide an API in Task.java, for example:

```Task<T> withDelay(final long time, final TimeUnit unit)```

to create a wrapper API using 

```public static <T> Task<T> async(final String name, final Function1<Context, Promise<? extends T>> func)```

and `context.createTimer`.

**Comment by junchuanwang** [comment]
Change merged. Closing
