### ISSUE TITLE
No rule to make target `../../version.properties'.  Stop.

### ISSUE THREAD

**Issue by micahstubbs** [linkedin/parseq#215]
When I follow the instructions [here](https://github.com/linkedin/parseq/tree/master/subprojects/parseq-tracevis#building) to build the parseq-tracevis subproject, I see this make error:

```bash
➜  parseq-tracevis git:(master) make dist
Makefile:27: ../../version.properties: No such file or directory
make: *** No rule to make target `../../version.properties'.  Stop.
```

what am I missing? is there another step that generates this missing `version.properties` file?

**Comment by bolobobo** [comment]
@micahstubbs Sorry to confuse you here. We migrated the build system from maven to Gradle last year and forgot the update this README. 
You can just run `./gradlew makeDist` to generate the tar.gz file.  And our team will fix this in our next release. Thank you for your reporting.

**Comment by micahstubbs** [comment]
ah hah, that makes sense 💡 

thanks for the explanation!

**Comment by bolobobo** [comment]
@micahstubbs This issue has been resolved in https://github.com/linkedin/parseq/pull/218/.
