### ISSUE TITLE
if-else condition based tasks associated with parent task

### ISSUE THREAD

**Issue by hiteshsharma** [linkedin/parseq#216]
I'm executing `TaskA` and based on failure/success of `TaskA` I want to execute `TaskB` and `TaskC`.

```
if (TaskA.isFailed()) {
  return TaskB;
} else {
  return TaskC;
}
```

Seems there's no way to achieve this currently. I tried using map and recover like
```
TaskA.map(result -> TaskC)
  .recover(e -> TaskB);
```
but this `.recover` is attached to result of `TaskC`. If I do
```
TaskA.recover(e -> TaskB)
  .map(TaskC);
```
then `TaskC` is attached to success of `TaskB` and not `TaskA`.

I tried using `transform` too but it does not return a `Task` but can only transform return value of a parent task like doing the following does not work
```
TaskA.transform(tryT -> {
  if (tryT.isFailed()) {
    return TaskB;
  } else {
    return TaskC;
  }
});
```
The overall return value should be the return value of Task which executed in the end (i.e. `TaskB` or `TaskC`). Is it currently possible to achieve this?

**Comment by hiteshsharma** [comment]
Can't even use `andThen` as the task passed does not depend on result of parent Task and might not even wait for parent Task to complete

**Comment by mchen07** [comment]
Have you looked at `toTry` method of Task? https://static.javadoc.io/com.linkedin.parseq/parseq/3.0.7/com/linkedin/parseq/Task.html#toTry--

**Comment by hiteshsharma** [comment]
Thanks @mchen07 that works. closing the issue
