### ISSUE TITLE
Tasks.<T>par(emptyIterable<? extends Task<? extends T>>) should not throw IllegalArgumentException

### ISSUE THREAD

**Issue by yborovikov** [linkedin/parseq#22]
It should be ok to call _Tasks.<T>par(tasks)_ with tasks being an empty collection. When run, such parallel task's Promise would resolve to an empty _List<T>_.
Currently client code has to check if task accumulator is empty and arrange different composition of tasks instead:

``` java
{
  Collection<Task<Foo>> fooTasks = buildFooTasks(...); // may return empty collection
  Task<Bar> mergeFoosTask = new MergeFoosTask();
  Task<Bar> computeAndMerge = fooTasks.isEmpty ? mergeFoosTask : Tasks.seq(Tasks.par(fooTasks), mergeFoosTask);
  ...
}
```

**Comment by jodzga** [comment]
I agree this should have been the behavior from the very beginning but unfortunately such change is backwards incompatible and might break existing code.

**Comment by yborovikov** [comment]
@jodzga, do you mean there could be code that relies on `Tasks.par()` to throw an `IllegalArgumentException` in case an empty collection is passed as its argument?
Or on ultimate `List<T>` being non-empty?

**Comment by jodzga** [comment]
I can imagine both.
Our current thinking is to create Task.par() with better semantics, deprecate Tasks.par() and point it to Task.par().

**Comment by yborovikov** [comment]
Yeah, that should work. Otherwise developers would have to introduce their own sets of utility classes. No big deal, but it's good to have one from the authors :)

**Comment by dimapilis** [comment]
I've submitted a PR for this issue last week, which should be merged sometime this week: https://github.com/linkedin/parseq/pull/113

**Comment by dimapilis** [comment]
@jodzga Should be safe to close this issue now. :)
