### ISSUE TITLE
Is it possible to synchronize tasks? 

### ISSUE THREAD

**Issue by yaseco** [linkedin/parseq#223]
Suppose we have a `List<City> cities` and we also have `getStreets(City city)` which returns `List<Street>`. Let's assume that every `Street` needs to be processed with some IO request.

I would like to have a reasonable control over the processing. For example, emit the next city only when all the streets of the current city were processed.  

Is it possible? How would you do that?

**Comment by roopalJazz** [comment]
Task.callable() achieves that, all the execution is done sequentially

**Comment by junchuanwang** [comment]
The question is not so clear.

If I am understanding correctly, here is what supposed to be done

Let's say you create one single Task for `getStreets(City city)` with single city.

Then basically what is being asked is to sequentially process all the cities, which can be achieved by `Tasks.seq()` interface.
