### ISSUE TITLE
Use long instead Long in ShallowTraceBuilder to avoid memory over-use for parseq tracing.

### ISSUE THREAD

**Issue by mchen07** [linkedin/parseq#244]
Currently `ShallowTraceBuilder` is using `Long` for `_id`, `_startNanos`, `_endNanos`, `_pendingNanos`. When a plan involves too many tasks (both system and user-defined), we will have too many instances of `ShallowTraceBuilder`, which leads to memory over-use. We should optimize the code to see if they can be replaced by `long`.

**Comment by mchen07** [comment]
When we make this optimization, please keep public API unchanged to avoid breaking any open-source users.

**Comment by junchuanwang** [comment]
This issue is closed since change pushed by @aman1309  [PR#267](https://github.com/linkedin/parseq/pull/267)
