### ISSUE TITLE
Broken link in Wiki regarding parsec-exec

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [linkedin/parseq#245]
In [this link](https://github.com/linkedin/parseq/wiki/User's-Guide#integrating-with-parseq), the `parseq-exec` link under the second bullet point is broken; it points to [here](https://github.com/linkedin/parseq/tree/contrib/parseq-exec,) where as the correct link is [this](https://github.com/linkedin/parseq/tree/functional/contrib/parseq-exec).

**Comment by evanw555** [comment]
Fixed. Thanks for pointing this out
