### ISSUE TITLE
Flaky test in TestExecutionMonitor

### ISSUE THREAD

**Issue by evanw555** [linkedin/parseq#251]
I've noticed the Travis build is a little flaky and fails maybe 20% of the time due to this unit test failure:

```
> Task :parseq:test
Gradle suite > Gradle test > com.linkedin.parseq.internal.TestExecutionMonitor.testStallsWithStuckThread FAILED
    java.lang.AssertionError at TestExecutionMonitor.java:108
503 tests completed, 1 failed, 3 skipped
> Task :parseq:test FAILED
FAILURE: Build failed with an exception.
```

We should resolve this so that the Travis build check is accurate.

**Comment by mchen07** [comment]
This is duplicate to https://github.com/linkedin/parseq/issues/161

**Comment by evanw555** [comment]
True. Closing this ticket as a duplicate to #161
