### ISSUE TITLE
Possible to cancel a running task?

### ISSUE THREAD

**Issue by Anmol-Singh-Jaggi** [linkedin/parseq#271]
Is it possible to cancel a running task?
I know that a thread cannot be stopped forcefully.
But will it be possible to atleast interrupt the task thread so that it receives an `InterruptedException()`?

```java
    Task<Void> t1 = Task.action(() -> {
      try {
        Thread.sleep(100000); // wait for 100 seconds 
    } catch (InterruptedException e) {
        System.out.println("Interrupted");
        throw new Error(e);
    }
    });
    engine.run(t1);
    System.out.println(t1.cancel(new Exception())); // cancel() is returning false.
    engine.shutdown();
    engine.awaitTermination(10, TimeUnit.SECONDS);
    // Engine still running.
```

Similarly, is there any way to forcefully shutdown the engine and kill all running tasks forcefully?

**Comment by junchuanwang** [comment]
Hi Anmol, 
Currently we don't support task cancel in that way. We know only cancel task by timeout and it is framework level control.

My question is whether you really need the cancel mechanism. Can I understand your use case? There might be other workaround to it.

**Comment by junchuanwang** [comment]
I will close this issue due to inactivity
