### ISSUE TITLE
Typo in wiki Par vs Seq example code

### ISSUE THREAD

**Issue by adambengis** [linkedin/parseq#290]
The [Execution Model Introduction wiki](https://github.com/linkedin/parseq/wiki/Execution-Model-Introduction) has a typo in the [Par vs Seq](https://github.com/linkedin/parseq/wiki/Execution-Model-Introduction#task-scheduling-par-vs-seq) discussion's last code example:

```java
Task<String> fetchGoogle = fetchBody("http://www.google.com");
Task<String> fetchBing = fetchBody("http://www.bing.com");
Task<String> processGoogle = fetchGoogle.andThen(this::processBodoogley);
Task<String> processGBing = fetchBing.andThen(this::processBody);
```

Though "processBodoogley" is hilarious and "processGBing" is pretty silly also, I believe the author meant "processBody" and "processBing", respectively, as in:

```java
Task<String> fetchGoogle = fetchBody("http://www.google.com");
Task<String> fetchBing = fetchBody("http://www.bing.com");
Task<String> processGoogle = fetchGoogle.andThen(this::processBody);
Task<String> processBing = fetchBing.andThen(this::processBody);
```

**Comment by karthikbalasub** [comment]
ha ha, good catch :)
Fixed now.
