### ISSUE TITLE
withTimeout does not interrupt running task

### ISSUE THREAD

**Issue by FossiFoo** [linkedin/parseq#60]
As far as i can tell, Task.withTimeout() does not seem to interrupt the running task at all.

Please see this gist for a pretty minimal test case: https://gist.github.com/FossiFoo/7de2231f24e7b0b5214e

**Comment by FossiFoo** [comment]
Maybe this is even expected with a Executors.newSingleThreadScheduledExecutor(), but Executors.newScheduledThreadPool( numCores ) as TimerScheduler does not work either.

**Comment by FossiFoo** [comment]
I came to the conclusion that i maybe should have been using Task.blocking instead of Task.action. Maybe the destinction of "long running" could be cleared up/added in the documentation.

Feel free to close.

**Comment by jodzga** [comment]
If you have a job that can "block" a thread for any reason (e.g. blocking IO, CPU intensive work etc.) then the best strategy is to offload that work onto a separate executor using Task.blocking().
You are right that documentation might have been more clear about that. I'll try to improve it.

Thanks for your comments!
